# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_start.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QWidget)

class Ui_Break_In_Box(object):
    def setupUi(self, Break_In_Box):
        if not Break_In_Box.objectName():
            Break_In_Box.setObjectName(u"Break_In_Box")
        Break_In_Box.resize(1024, 600)
        Break_In_Box.setMaximumSize(QSize(1024, 600))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush1)
        brush2 = QBrush(QColor(255, 255, 220, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush2)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush1)
        brush3 = QBrush(QColor(255, 255, 255, 127))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush3)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush1)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush3)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush1)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush1)
        brush4 = QBrush(QColor(0, 0, 0, 127))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush4)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush1)
#endif
        Break_In_Box.setPalette(palette)
        self.centralwidget = QWidget(Break_In_Box)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1024, 600))
        self.page_start = QWidget()
        self.page_start.setObjectName(u"page_start")
        self.page_start.setEnabled(True)
        self.lbl_start = QLabel(self.page_start)
        self.lbl_start.setObjectName(u"lbl_start")
        self.lbl_start.setGeometry(QRect(277, 40, 470, 160))
        palette1 = QPalette()
        brush5 = QBrush(QColor(165, 0, 0, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush3)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush1)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush3)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush1)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush2)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush4)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush1)
#endif
        self.lbl_start.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"October Crow"])
        font.setPointSize(36)
        self.lbl_start.setFont(font)
        self.pb_start_yes = QPushButton(self.page_start)
        self.pb_start_yes.setObjectName(u"pb_start_yes")
        self.pb_start_yes.setGeometry(QRect(120, 350, 270, 150))
        palette2 = QPalette()
        brush6 = QBrush(QColor(120, 6, 6, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        self.pb_start_yes.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"October Crow"])
        font1.setPointSize(73)
        self.pb_start_yes.setFont(font1)
        self.pb_start_yes.setStyleSheet(u"border-color: #780606;\n"
"border-style: outset;\n"
"background-color: black;")
        self.pb_start_no = QPushButton(self.page_start)
        self.pb_start_no.setObjectName(u"pb_start_no")
        self.pb_start_no.setGeometry(QRect(634, 350, 270, 150))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush7 = QBrush(QColor(0, 85, 0, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush7)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush7)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        self.pb_start_no.setPalette(palette3)
        font2 = QFont()
        font2.setPointSize(73)
        self.pb_start_no.setFont(font2)
        self.pb_start_no.setStyleSheet(u"border-style: outset;\n"
"background-color: black;")
        self.stackedWidget.addWidget(self.page_start)
        self.page_menu = QWidget()
        self.page_menu.setObjectName(u"page_menu")
        self.lst_menu = QListWidget(self.page_menu)
        self.lst_menu.setObjectName(u"lst_menu")
        self.lst_menu.setGeometry(QRect(30, 30, 964, 450))
        self.pb_admin_menu = QPushButton(self.page_menu)
        self.pb_admin_menu.setObjectName(u"pb_admin_menu")
        self.pb_admin_menu.setGeometry(QRect(110, 530, 110, 50))
        self.pb_back_menu = QPushButton(self.page_menu)
        self.pb_back_menu.setObjectName(u"pb_back_menu")
        self.pb_back_menu.setGeometry(QRect(880, 530, 110, 50))
        self.stackedWidget.addWidget(self.page_menu)
        self.page_admin = QWidget()
        self.page_admin.setObjectName(u"page_admin")
        self.pb_back_admin = QPushButton(self.page_admin)
        self.pb_back_admin.setObjectName(u"pb_back_admin")
        self.pb_back_admin.setGeometry(QRect(880, 530, 110, 50))
        self.stackedWidget.addWidget(self.page_admin)
        self.page_puzzle = QWidget()
        self.page_puzzle.setObjectName(u"page_puzzle")
        self.lbl_puzzle_nbr = QLabel(self.page_puzzle)
        self.lbl_puzzle_nbr.setObjectName(u"lbl_puzzle_nbr")
        self.lbl_puzzle_nbr.setGeometry(QRect(10, 10, 41, 31))
        font3 = QFont()
        font3.setPointSize(13)
        self.lbl_puzzle_nbr.setFont(font3)
        self.lbl_puzzle_descr = QLabel(self.page_puzzle)
        self.lbl_puzzle_descr.setObjectName(u"lbl_puzzle_descr")
        self.lbl_puzzle_descr.setGeometry(QRect(302, 0, 420, 80))
        self.lbl_puzzle_descr.setFont(font3)
        self.lbl_puzzle_descr.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pb_hint = QPushButton(self.page_puzzle)
        self.pb_hint.setObjectName(u"pb_hint")
        self.pb_hint.setGeometry(QRect(30, 530, 110, 50))
        self.pb_submit = QPushButton(self.page_puzzle)
        self.pb_submit.setObjectName(u"pb_submit")
        self.pb_submit.setGeometry(QRect(442, 530, 140, 50))
        self.pb_puzzle_back = QPushButton(self.page_puzzle)
        self.pb_puzzle_back.setObjectName(u"pb_puzzle_back")
        self.pb_puzzle_back.setGeometry(QRect(880, 530, 110, 50))
        self.stacked_puzzle_content = QStackedWidget(self.page_puzzle)
        self.stacked_puzzle_content.setObjectName(u"stacked_puzzle_content")
        self.stacked_puzzle_content.setGeometry(QRect(30, 80, 964, 451))
        self.page_code_puzzle = QWidget()
        self.page_code_puzzle.setObjectName(u"page_code_puzzle")
        self.lbl_hint = QLabel(self.page_code_puzzle)
        self.lbl_hint.setObjectName(u"lbl_hint")
        self.lbl_hint.setGeometry(QRect(10, 390, 121, 71))
        font4 = QFont()
        font4.setPointSize(10)
        self.lbl_hint.setFont(font4)
        self.led_code = QLineEdit(self.page_code_puzzle)
        self.led_code.setObjectName(u"led_code")
        self.led_code.setGeometry(QRect(332, 170, 300, 50))
        palette4 = QPalette()
        brush8 = QBrush(QColor(250, 0, 0, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush8)
        brush9 = QBrush(QColor(252, 0, 0, 255))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush9)
        brush10 = QBrush(QColor(255, 0, 0, 127))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush8)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush9)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush10)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        self.led_code.setPalette(palette4)
        font5 = QFont()
        font5.setFamilies([u"October Crow"])
        font5.setPointSize(22)
        font5.setBold(False)
        self.led_code.setFont(font5)
        self.led_code.setStyleSheet(u"QLineEdit {border:none};")
        self.led_code.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stacked_puzzle_content.addWidget(self.page_code_puzzle)
        self.page_screen_puzzle = QWidget()
        self.page_screen_puzzle.setObjectName(u"page_screen_puzzle")
        self.pb_led1_off = QPushButton(self.page_screen_puzzle)
        self.pb_led1_off.setObjectName(u"pb_led1_off")
        self.pb_led1_off.setGeometry(QRect(280, 260, 88, 34))
        self.pb_led1_on = QPushButton(self.page_screen_puzzle)
        self.pb_led1_on.setObjectName(u"pb_led1_on")
        self.pb_led1_on.setGeometry(QRect(280, 220, 88, 34))
        self.pb_led2_off = QPushButton(self.page_screen_puzzle)
        self.pb_led2_off.setObjectName(u"pb_led2_off")
        self.pb_led2_off.setGeometry(QRect(630, 250, 88, 34))
        self.pb_led2_on = QPushButton(self.page_screen_puzzle)
        self.pb_led2_on.setObjectName(u"pb_led2_on")
        self.pb_led2_on.setGeometry(QRect(630, 210, 88, 34))
        self.stacked_puzzle_content.addWidget(self.page_screen_puzzle)
        self.lbl_countdown_puzzle = QLabel(self.page_puzzle)
        self.lbl_countdown_puzzle.setObjectName(u"lbl_countdown_puzzle")
        self.lbl_countdown_puzzle.setGeometry(QRect(870, 10, 110, 50))
        palette5 = QPalette()
        brush11 = QBrush(QColor(255, 0, 0, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        self.lbl_countdown_puzzle.setPalette(palette5)
        font6 = QFont()
        font6.setFamilies([u"Digital-7"])
        font6.setPointSize(30)
        self.lbl_countdown_puzzle.setFont(font6)
        self.lbl_hints_used = QLabel(self.page_puzzle)
        self.lbl_hints_used.setObjectName(u"lbl_hints_used")
        self.lbl_hints_used.setGeometry(QRect(160, 530, 70, 50))
        font7 = QFont()
        font7.setPointSize(12)
        self.lbl_hints_used.setFont(font7)
        self.lbl_hints_used.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.stackedWidget.addWidget(self.page_puzzle)
        Break_In_Box.setCentralWidget(self.centralwidget)

        self.retranslateUi(Break_In_Box)

        self.stackedWidget.setCurrentIndex(3)
        self.stacked_puzzle_content.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Break_In_Box)
    # setupUi

    def retranslateUi(self, Break_In_Box):
        Break_In_Box.setWindowTitle(QCoreApplication.translate("Break_In_Box", u"MainWindow", None))
        self.lbl_start.setText(QCoreApplication.translate("Break_In_Box", u"Are you ready to enter?", None))
        self.pb_start_yes.setText(QCoreApplication.translate("Break_In_Box", u"Yes", None))
        self.pb_start_no.setText(QCoreApplication.translate("Break_In_Box", u"No", None))
        self.pb_admin_menu.setText(QCoreApplication.translate("Break_In_Box", u"Admin", None))
        self.pb_back_menu.setText(QCoreApplication.translate("Break_In_Box", u"Back", None))
        self.pb_back_admin.setText(QCoreApplication.translate("Break_In_Box", u"Back", None))
        self.lbl_puzzle_nbr.setText(QCoreApplication.translate("Break_In_Box", u"-1/-1", None))
        self.lbl_puzzle_descr.setText(QCoreApplication.translate("Break_In_Box", u"Describtion", None))
        self.pb_hint.setText(QCoreApplication.translate("Break_In_Box", u"Hint", None))
        self.pb_submit.setText(QCoreApplication.translate("Break_In_Box", u"Submit", None))
        self.pb_puzzle_back.setText(QCoreApplication.translate("Break_In_Box", u"Back", None))
        self.lbl_hint.setText(QCoreApplication.translate("Break_In_Box", u"TextLabel", None))
        self.led_code.setPlaceholderText(QCoreApplication.translate("Break_In_Box", u"Enter the code...", None))
        self.pb_led1_off.setText(QCoreApplication.translate("Break_In_Box", u"led1 off", None))
        self.pb_led1_on.setText(QCoreApplication.translate("Break_In_Box", u"Led1 on", None))
        self.pb_led2_off.setText(QCoreApplication.translate("Break_In_Box", u"led2 off", None))
        self.pb_led2_on.setText(QCoreApplication.translate("Break_In_Box", u"led2 on", None))
        self.lbl_countdown_puzzle.setText(QCoreApplication.translate("Break_In_Box", u"09:99", None))
        self.lbl_hints_used.setText(QCoreApplication.translate("Break_In_Box", u"-1/-1", None))
    # retranslateUi

